physical_1 = [
    "Laptop",
    "Smartphone",
    "Television",
    "Refrigerator",
    "Washing Machine",
    "Air Conditioner",
    "Microwave Oven",
    "Mixer Grinder",
    "Gas Stove",
    "Iron Box",
    "Vacuum Cleaner",
    "Electric Kettle",
    "Sewing Machine",
    "Hair Dryer",
    "Water Purifier",
    "Induction Cooktop",
    "Dishwasher",
    "Air Purifier",
    "Toaster",
    "Juicer",
    "Digital Camera",
    "Gaming Console",
    "Headphones",
    "Portable Speaker",
    "Fitness Tracker",
    "Smart Watch",
    "Tablet",
    "Printer",
    "Scanner",
    "External Hard Drive",
    "USB Flash Drive",
    "Keyboard",
    "Mouse",
    "Router",
    "WiFi Extender",
    "Projector",
    "Monitor",
    "Graphics Card",
    "Motherboard",
    "RAM",
    "Power Supply Unit",
    "Optical Drive",
    "CPU Cooler",
    "Solid State Drive",
    "HDMI Cable",
    "Surge Protector",
    "Desk Lamp",
    "Office Chair",
    "Stationery Set",
    "Notebook",
    "Fountain Pen",
    "Pencil",
    "Eraser",
    "Stapler",
    "Tape Dispenser",
    "Marker Pens",
    "Highlighter",
    "Whiteboard",
    "Corkboard",
    "Paper Shredder",
    "File Cabinet",
    "Bookshelf",
    "Desk Organizer",
    "Wall Clock",
    "Floor Lamp",
    "Sofa",
    "Dining Table",
    "Bed",
    "Wardrobe",
    "Dressing Table",
    "Coffee Table",
    "TV Stand",
    "Bookcase",
    "Recliner",
    "Mattress",
    "Bed Sheets",
    "Pillow",
    "Curtains",
    "Carpet",
    "Wall Art",
    "Photo Frame",
    "Vase",
    "Tablecloth",
    "Cushion Covers",
    "Candle Holder",
    "Mug",
    "Dinner Set",
    "Cookware Set",
    "Cutlery Set",
    "Wine Glasses",
    "Tea Set",
    "Coffee Maker",
    "Blender",
    "Food Processor",
    "Knife Set",
    "Bakeware Set",
    "Grill Pan",
    "Frying Pan",
    "Saucepan",
    "Pressure Cooker",
    "Oven Mitts",
    "Apron",
    "Garment Steamer",
    "Sewing Kit",
    "Hammer",
    "Screwdriver Set",
    "Wrench Set",
    "Pliers",
    "Tape Measure",
    "Saw",
    "Drill",
    "Level",
]

physical_2 = [
    "Ladder",
    "Garden Hose",
    "Lawn Mower",
    "Wheelbarrow",
    "Shovel",
    "Rake",
    "Gardening Gloves",
    "Pruning Shears",
    "Sprinkler",
    "Garden Bench",
    "Garden Gnome",
    "Bird Feeder",
    "Bird Bath",
    "Garden Trowel",
    "Grill",
    "Patio Furniture",
    "Outdoor Heater",
    "Gazebo",
    "Hammock",
    "Swing Set",
    "Bicycle",
    "Scooter",
    "Roller Skates",
    "Skateboard",
    "Helmet",
    "Knee Pads",
    "Elbow Pads",
    "Frisbee",
    "Kite",
    "Camping Tent",
    "Sleeping Bag",
    "Camping Stove",
    "Lantern",
    "Hiking Backpack",
    "Binoculars",
    "Compass",
    "GPS Device",
    "Hiking Boots",
    "Multi-tool",
    "Fishing Rod",
    "Fishing Reel",
    "Fishing Bait",
    "Fishing Line",
    "Fishing Net",
    "Basketball",
    "Soccer Ball",
    "Football",
    "Baseball Glove",
    "Baseball Bat",
    "Tennis Racket",
    "Badminton Racket",
    "Golf Clubs",
    "Golf Balls",
    "Golf Cart",
    "Yoga Mat",
    "Dumbbells",
    "Treadmill",
    "Exercise Bike",
    "Rowing Machine",
    "Jump Rope",
    "Resistance Bands",
    "Punching Bag",
    "Boxing Gloves",
    "Ankle Weights",
    "Swimming Goggles",
    "Swimming Cap",
    "Swimsuit",
    "Surfboard",
    "Wetsuit",
    "Snorkel",
    "Fins",
    "Life Jacket",
    "Kayak",
    "Canoe",
    "Pool Float",
    "Beach Umbrella",
    "Beach Towel",
    "Beach Ball",
    "Sand Toys",
    "Picnic Basket",
    "Cooler",
    "Portable Grill",
    "Lawn Chair",
    "Bug Zapper",
    "Sunglasses",
    "Sun Hat",
    "Flip Flops",
    "Beach Bag",
    "Sunscreen",
    "Inflatable Boat",
    "Paddleboard",
    "Beach Tent",
    "Metal Detector",
    "Volleyball Net",
    "Pool Noodles",
    "Water Guns",
    "Water Balloons",
    "Slip and Slide",
    "Trampoline",
    "Playground Slide",
    "Swing",
    "Seesaw",
    "Sandbox",
    "Playhouse",
]

physical_3 = [
    "Electric Fan",
    "Space Heater",
    "Humidifier",
    "Dehumidifier",
    "Shirt",
    "Air Purifier",
    "Electric Blanket",
    "Oil Heater",
    "Ceiling Fan",
    "Fireplace",
    "Infrared Heater",
    "Washing Machine",
    "Dryer",
    "Laundry Basket",
    "Ironing Board",
    "Clothes Hanger",
    "Vacuum Cleaner",
    "Carpet Cleaner",
    "Mop",
    "Broom",
    "Dustpan",
    "Garbage Bin",
    "Recycling Bin",
    "Compost Bin",
    "Cleaning Cloth",
    "Dish Rack",
    "Dish Soap",
    "Sponge",
    "Oven Cleaner",
    "Glass Cleaner",
    "Trash Bags",
    "Paper Towels",
    "Toilet Brush",
    "Plunger",
    "Bathroom Cleaner",
    "Toilet Paper",
    "Hand Soap",
    "Shower Curtain",
    "Bath Mat",
    "Bath Towel",
    "Toothbrush",
    "Toothpaste",
    "Mouthwash",
    "Floss",
    "Razor",
    "Shaving Cream",
    "Shampoo",
    "Conditioner",
    "Body Wash",
    "Lotion",
    "Deodorant",
    "Perfume",
    "Cologne",
    "Hair Gel",
    "Hairspray",
    "Makeup",
    "Lipstick",
    "Mascara",
    "Eyeliner",
    "Foundation",
    "Nail Polish",
    "Nail Polish Remover",
    "Face Wash",
    "Moisturizer",
    "Sunscreen",
    "Hair Dryer",
    "Curling Iron",
    "Flat Iron",
    "Hair Brush",
    "Comb",
    "Bed",
    "Mattress",
    "Pillow",
    "Sheet Set",
    "Comforter",
    "Nightstand",
    "Lamp",
    "Alarm Clock",
    "Dresser",
    "Mirror",
    "Sofa",
    "Coffee Table",
    "TV Stand",
    "Bookshelf",
    "Dining Table",
    "Dining Chairs",
    "Curtains",
    "Blinds",
    "Rug",
    "Candles",
    "Picture Frame",
    "Wall Art",
    "Vase",
    "Decorative Bowl",
    "Figurines",
    "Lawn Mower",
    "Weed Whacker",
    "Leaf Blower",
    "Hedge Trimmer",
    "Pruner",
    "Garden Hose",
    "Sprinkler",
    "Fertilizer",
    "Seeds",
    "Pesticide",
    "Snow Blower",
    "Shovel",
    "Salt",
    "Ice Scraper",
    "Snow Brush",
]

physical_4 = [
    "Waffle Maker",
    "Blender",
    "Toaster",
    "Microwave",
    "Electric Kettle",
    "Coffee Maker",
    "Food Processor",
    "Slow Cooker",
    "Juicer",
    "Rice Cooker",
    "Air Fryer",
    "Grill",
    "Sandwich Maker",
    "Bread Maker",
    "Deep Fryer",
    "Ice Cream Maker",
    "Soda Maker",
    "Electric Skillet",
    "Stove",
    "Oven",
    "Refrigerator",
    "Freezer",
    "Dishwasher",
    "Garbage Disposal",
    "Water Filter",
    "Electric Can Opener",
    "Electric Knife",
    "Food Dehydrator",
    "Popcorn Maker",
    "Electric Griddle",
    "Pasta Maker",
    "Meat Grinder",
    "Vacuum Sealer",
    "Milk Frother",
    "Tea Infuser",
    "Cookie Sheet",
    "Baking Dish",
    "Mixing Bowl",
    "Measuring Cups",
    "Measuring Spoons",
    "Whisk",
    "Spatula",
    "Ladle",
    "Tongs",
    "Peeler",
    "Grater",
    "Corkscrew",
    "Can Opener",
    "Garlic Press",
    "Pastry Brush",
    "Rolling Pin",
    "Muffin Tin",
    "Cake Pan",
    "Pie Dish",
    "Cooling Rack",
    "Cutting Board",
    "Knife Set",
    "Pots and Pans",
    "Colander",
    "Salad Spinner",
    "Dinner Plates",
    "Bowls",
    "Glasses",
    "Mugs",
    "Silverware",
    "Wine Glasses",
    "Champagne Flutes",
    "Cocktail Shaker",
    "Coasters",
    "Tablecloth",
    "Napkins",
    "Placemats",
    "Salt and Pepper Shakers",
    "Sugar Bowl",
    "Butter Dish",
    "Toothpicks",
    "Serving Tray",
    "Serving Bowl",
    "Gravy Boat",
    "Carving Knife",
    "Bread Knife",
    "Steak Knives",
    "Pizza Cutter",
    "Ice Cream Scoop",
    "Nutcracker",
    "Potato Masher",
    "Salad Tongs",
    "Wine Rack",
    "Spice Rack",
    "Paper Towel Holder",
    "Bottle Opener",
    "Ice Bucket",
    "Ice Tray",
    "Thermos",
    "Lunch Box",
    "Reusable Water Bottle",
    "Food Storage Containers",
    "Ziplock Bags",
    "Aluminum Foil",
    "Plastic Wrap",
    "Trash Can",
    "Compost Bin",
    "Recycling Bin",
    "Dustpan",
    "Broom",
    "Mop",
    "Bucket",
    "Cleaning Spray",
    "Sponge",
    "Dish Soap",
    "Laundry Detergent",
    "Fabric Softener",
    "Bleach",
    "Stain Remover",
    "Laundry Basket",
]

physical_5 = [
    "Window Cleaner",
    "Floor Polish",
    "Toilet Cleaner",
    "Plunger",
    "Toilet Brush",
    "Feather Duster",
    "Microfiber Cloth",
    "Glass Cleaner",
    "Air Freshener",
    "Candle",
    "Flashlight",
    "Batteries",
    "Extension Cord",
    "Surge Protector",
    "Light Bulbs",
    "Hammer",
    "Screwdriver",
    "Wrench",
    "Pliers",
    "Tape Measure",
    "Level",
    "Utility Knife",
    "Stud Finder",
    "Saw",
    "Drill",
    "Sander",
    "Nails",
    "Screws",
    "Anchors",
    "Glue Gun",
    "Wood Glue",
    "Duct Tape",
    "Masking Tape",
    "Painter’s Tape",
    "Chalk Line",
    "Ladder",
    "Work Bench",
    "Vice",
    "C-Clamps",
    "Safety Glasses",
    "Ear Plugs",
    "Dust Mask",
    "First Aid Kit",
    "Fire Extinguisher",
    "Smoke Detector",
    "Carbon Monoxide Detector",
    "Security Camera",
    "Door Lock",
    "Safe",
    "Filing Cabinet",
    "Paper Shredder",
    "Stationary",
    "Pen",
    "Pencil",
    "Marker",
    "Highlighter",
    "Eraser",
    "Sharpener",
    "Paper Clips",
    "Stapler",
    "Staple Remover",
    "Binder Clips",
    "Rubber Bands",
    "Envelope",
    "Notebook",
    "Notepad",
    "Post-it Notes",
    "Index Cards",
    "File Folders",
    "Binder",
    "Hole Punch",
    "Scissors",
    "Ruler",
    "Calculator",
    "Printer",
    "Ink Cartridges",
    "Printer Paper",
    "USB Drive",
    "External Hard Drive",
    "SD Card",
    "Keyboard",
    "Mouse",
    "Monitor",
    "Webcam",
    "Speakers",
    "Headphones",
    "Microphone",
    "Laptop Stand",
    "Phone Stand",
    "Charging Cable",
    "Phone Case",
    "Screen Protector",
    "Tablet",
    "E-reader",
    "Smart Watch",
    "Fitness Tracker",
    "Game Console",
    "Video Games",
    "Remote Control",
    "TV Mount",
    "DVD Player",
    "Blu-ray Player",
    "Projector",
    "Camera",
    "Tripod",
    "Flash",
    "Lens",
    "Memory Card",
    "Camera Bag",
    "Photo Printer",
]

physical_6 = [
    "Photo Paper",
    "Picture Frame",
    "Album",
    "Canvas",
    "Easel",
    "Paintbrush",
    "Palette",
    "Acrylic Paint",
    "Oil Paint",
    "Watercolor Paint",
    "Pastels",
    "Colored Pencils",
    "Crayons",
    "Markers",
    "Sketchbook",
    "Drawing Paper",
    "Construction Paper",
    "Cardstock",
    "Glue Stick",
    "Mod Podge",
    "Scrapbooking Supplies",
    "Stamps",
    "Ink Pad",
    "Stencils",
    "Ribbon",
    "Fabric",
    "Thread",
    "Needles",
    "Sewing Machine",
    "Embroidery Hoop",
    "Buttons",
    "Zippers",
    "Pins",
    "Thimble",
    "Fabric Scissors",
    "Yarn",
    "Crochet Hook",
    "Knitting Needles",
    "Beads",
    "Jewelry Wire",
    "Jewelry Pliers",
    "Jewelry Clasps",
    "Charm",
    "Gemstones",
    "Hot Glue Gun",
    "Hot Glue Sticks",
    "Washi Tape",
    "Decorative Tape",
    "Stickers",
    "Decals",
    "Sequins",
    "Glitter",
    "Foam Sheets",
    "Felt Sheets",
    "Pipe Cleaners",
    "Pompoms",
    "Googly Eyes",
    "Feathers",
    "Clay",
    "Molding Tools",
    "Chisels",
    "Wood Carving Knife",
    "Sandpaper",
    "Varnish",
    "Wood Stain",
    "Lacquer",
    "Latex Paint",
    "Spray Paint",
    "Painter’s Brush",
    "Roller Brush",
    "Drop Cloth",
    "Paint Tray",
    "Caulk",
    "Caulking Gun",
    "Grout",
    "Tile Cutter",
    "Trowel",
    "Sponge",
    "Bucket",
    "Mop",
    "Broom",
    "Dustpan",
    "Trash Bags",
    "Cleaning Gloves",
    "Apron",
    "Oven Mitts",
    "Pot Holders",
    "Trivet",
    "Dish Towel",
    "Sponge",
    "Dish Rack",
    "Cutting Board",
    "Knife Sharpener",
    "Pepper Mill",
    "Spice Grinder",
    "Oil Dispenser",
    "Vinegar Dispenser",
    "Salad Dressing Mixer",
    "Salad Spinner",
    "Garlic Press",
    "Citrus Juicer",
    "Apple Corer",
    "Cherry Pitter",
    "Nutcracker",
    "Wine Opener",
    "Bottle Opener",
    "Can Opener",
    "Ice Cream Scoop",
    "Meat Thermometer",
    "Kitchen Timer",
    "Food Scale",
    "Measuring Cups",
    "Measuring Spoons",
    "Mixing Bowls",
    "Colander",
    "Grater",
    "Zester",
    "Mandoline Slicer",
    "Vegetable Peeler",
    "Spiralizer",
    "Mortar and Pestle",
    "Rolling Pin",
    "Pastry Brush",
    "Pastry Cutter",
    "Cookie Cutter",
    "Computer",
    "Leggings",
]

digital_1 = [
    "Salesforce",
    "Zoom",
    "Slack",
    "Microsoft 365",
    "Google Workspace",
    "Dropbox",
    "Shopify",
    "Adobe Creative Cloud",
    "Mailchimp",
    "HubSpot",
    "Asana",
    "Trello",
    "Jira",
    "Confluence",
    "Bitbucket",
    "GitHub",
    "GitLab",
    "AWS",
    "Azure",
    "Google Cloud Platform",
    "Oracle Cloud",
    "IBM Cloud",
    "Alibaba Cloud",
    "Zoho",
    "SAP Concur",
    "QuickBooks",
    "Zendesk",
    "ServiceNow",
    "Splunk",
    "Atlassian",
    "SurveyMonkey",
    "DocuSign",
    "Twilio",
    "Tableau",
    "Workday",
    "Box",
    "Wrike",
    "Freshdesk",
    "NetSuite",
    "Evernote",
    "Monday.com",
    "Smartsheet",
    "ClickUp",
    "Basecamp",
    "Airtable",
    "Notion",
    "Zapier",
    "Intercom",
    "Buffer",
    "Hootsuite",
    "Sprout Social",
    "Freshservice",
    "Kaspersky",
    "Norton",
    "McAfee",
    "Docusign",
    "Adobe Sign",
    "PandaDoc",
    "Salesforce CPQ",
    "BigCommerce",
    "WooCommerce",
    "Magento",
    "Squarespace",
    "Wix",
    "Webflow",
    "Duda",
    "Stripe",
    "PayPal",
    "Square",
    "Braintree",
    "Worldpay",
    "Adyen",
    "Skrill",
    "Klaviyo",
    "Marketo",
    "Pardot",
    "ActiveCampaign",
    "Infusionsoft",
    "Drift",
    "Teachable",
    "Thinkific",
    "Kajabi",
    "Udemy",
    "Coursera",
    "Skillshare",
    "LinkedIn Learning",
    "Khan Academy",
    "Pluralsight",
    "Edx",
    "Udacity",
    "Moodle",
    "Blackboard",
    "Instructure",
    "Google Classroom",
    "WebEx",
    "GoToMeeting",
    "RingCentral",
    "BlueJeans",
    "Microsoft Teams",
    "Zoho Meeting",
    "Join.me",
    "AnyMeeting",
    "Yammer",
    "Twitch",
    "Vimeo",
    "Wistia",
    "Brightcove",
    "Kaltura",
    "Panopto",
    "Zendesk Chat",
    "LiveChat",
    "Tawk.to",
    "Pure Chat",
    "Olark",
]

digital_2 = [
    "Freshchat",
    "Zopim",
    "Comm100",
    "SnapEngage",
    "Intercom Messenger",
    "Help Scout",
    "Kayako",
    "Groove",
    "Desk.com",
    "SupportBee",
    "Freshcaller",
    "Dialpad",
    "Ringio",
    "Grasshopper",
    "Nextiva",
    "Vonage",
    "8x8",
    "Jive",
    "Mitel",
    "3CX",
    "Calendly",
    "Acuity Scheduling",
    "Doodle",
    "ScheduleOnce",
    "YouCanBook.me",
    "vCita",
    "Booker",
    "TimeTrade",
    "Appointy",
    "Setmore",
    "Insightly",
    "Zoho CRM",
    "Salesforce CRM",
    "HubSpot CRM",
    "Pipedrive",
    "Freshsales",
    "Nimble",
    "Capsule CRM",
    "Agile CRM",
    "Bitrix24",
    "Miro",
    "Lucidchart",
    "Draw.io",
    "Creately",
    "Gliffy",
    "XMind",
    "MindMeister",
    "MindMup",
    "Coggle",
    "ConceptDraw MINDMAP",
    "BuzzSumo",
    "Moz",
    "SEMrush",
    "Ahrefs",
    "Google Analytics",
    "Google Search Console",
    "SpyFu",
    "KWFinder",
    "Majestic",
    "Alexa",
    "Hotjar",
    "Crazy Egg",
    "Optimizely",
    "Unbounce",
    "Visual Website Optimizer",
    "Mixpanel",
    "Kissmetrics",
    "Heap",
    "Amplitude",
    "Segment",
    "Grammarly",
    "Hemingway Editor",
    "ProWritingAid",
    "Scrivener",
    "Final Draft",
    "Evernote",
    "OneNote",
    "Bear",
    "Simplenote",
    "Google Keep",
    "Toggl",
    "Harvest",
    "RescueTime",
    "Clockify",
    "Time Doctor",
    "Freshbooks",
    "Wave",
    "QuickBooks Online",
    "Xero",
    "Sage Business Cloud Accounting",
    "Odoo",
    "Intuit Mint",
    "Personal Capital",
    "Quicken",
    "Expensify",
    "Receipt Bank",
    "Rydoo",
    "Concur Expense",
    "Greenhouse",
    "Workable",
    "Lever",
    "BambooHR",
    "JazzHR",
    "Zoho Recruit",
    "Breezy HR",
    "iCIMS Talent Acquisition",
    "SmartRecruiters",
    "Bullhorn",
]

digital_3 = [
    "Gusto",
    "Paychex",
    "ADP Workforce",
    "Zenefits",
    "Square Payroll",
    "QuickBooks Payroll",
    "Namely",
    "SurePayroll",
    "Patriot Software",
    "Wave Payroll",
    "Ceridian Dayforce",
    "UltiPro",
    "Workday HCM",
    "Kronos Workforce Ready",
    "SAP SuccessFactors",
    "Oracle HCM Cloud",
    "SumTotal",
    "PeopleSoft",
    "Zoho People",
    "BambooHR",
    "Ascentis",
    "BirdDogHR",
    "HR Cloud",
    "WorkBright",
    "Workforce Now",
    "Infor HCM",
    "Microsoft Dynamics 365 Human Resources",
    "CakeHR",
    "People HR",
    "Sage HRMS",
    "1Password",
    "LastPass",
    "Dashlane",
    "NordPass",
    "Keeper",
    "Bitwarden",
    "LogMeOnce",
    "Sticky Password",
    "True Key",
    "Enpass",
    "Norton 360",
    "McAfee Total Protection",
    "Kaspersky Total Security",
    "Bitdefender Total Security",
    "Webroot SecureAnywhere",
    "Trend Micro Maximum Security",
    "Avira Prime",
    "Sophos Home Premium",
    "Panda Dome Advanced",
    "ESET Smart Security Premium",
    "Malwarebytes Premium",
    "Avast Premium Security",
    "AVG Internet Security",
    "VIPRE Advanced Security",
    "F-Secure SAFE",
    "Comodo Internet Security",
    "ZoneAlarm Extreme Security",
    "G DATA Total Security",
    "NortonLifeLock",
    "Microsoft Defender",
    "Canvas",
    "Schoology",
    "Moodle",
    "Edmodo",
    "Google Classroom",
    "Blackboard Learn",
    "D2L Brightspace",
    "SAP Litmos",
    "Adobe Captivate Prime",
    "Docebo",
    "TalentLMS",
    "LearnUpon",
    "Thinkific",
    "Teachable",
    "Kajabi",
    "Absorb LMS",
    "360Learning",
    "Adobe Connect",
    "WebEx Training Center",
    "GoToTraining",
    "Zoom Video Webinars",
    "Cisco WebEx Events",
    "Adobe Connect Webinars",
    "Microsoft Teams Live Events",
    "ON24",
    "BlueJeans Events",
    "Zoho Backstage",
    "ClickMeeting",
    "GetResponse",
    "EasyWebinar",
    "Demio",
    "WebinarJam",
    "EverWebinar",
    "GoToWebinar",
    "Livestorm",
    "WebinarNinja",
    "AnyMeeting",
    "BigMarker",
    "Zoom Video Conferencing",
    "Microsoft Teams",
    "Cisco WebEx",
    "Google Meet",
    "Zoho Meeting",
    "GoToMeeting",
    "RingCentral Video",
    "BlueJeans",
    "Adobe Connect",
    "Join.me",
    "LogMeIn",
    "TeamViewer",
    "AnyDesk",
    "Splashtop",
    "Zoho Assist",
    "ConnectWise Control",
    "BeyondTrust Remote Support",
]

digital_4 = [
    "Airtable",
    "Smartsheet",
    "Monday.com",
    "Asana",
    "Trello",
    "Jira",
    "ClickUp",
    "Wrike",
    "Basecamp",
    "Teamwork",
    "Podio",
    "Zoho Projects",
    "Microsoft Project",
    "ProofHub",
    "Clarizen",
    "Redmine",
    "Workzone",
    "FunctionFox",
    "ActiveCollab",
    "Planio",
    "Zendesk",
    "Freshdesk",
    "Zoho Desk",
    "ServiceNow",
    "Kayako",
    "Intercom",
    "Help Scout",
    "Groove",
    "LiveAgent",
    "Gorgias",
    "HubSpot Service Hub",
    "Kustomer",
    "TeamSupport",
    "HappyFox",
    "Sharpen",
    "Salesforce Service Cloud",
    "SAP Service Cloud",
    "Oracle Service Cloud",
    "Microsoft Dynamics 365 Customer Service",
    "Freshservice",
    "JitBit HelpDesk",
    "SolarWinds Service Desk",
    "SysAid",
    "ManageEngine ServiceDesk Plus",
    "Spiceworks Help Desk",
    "ConnectWise Manage",
    "Autotask PSA",
    "Tigerpaw",
    "Kaseya BMS",
    "Accelo",
    "N-able MSP Manager",
    "HarmonyPSA",
    "Atera",
    "Pulseway PSA",
    "Promys PSA",
    "Autodesk AutoCAD",
    "Adobe Photoshop",
    "Microsoft Visio",
    "Adobe Illustrator",
    "Sketch",
    "CorelDRAW",
    "Inkscape",
    "GIMP",
    "Canva",
    "Figma",
    "Adobe XD",
    "Axure RP",
    "Balsamiq Mockups",
    "Mockplus",
    "Wireframe.cc",
    "Fluid UI",
    "MockFlow",
    "Moqups",
    "SketchFlow",
    "Adobe InDesign",
    "QuarkXPress",
    "Scribus",
    "Microsoft Publisher",
    "Lucidpress",
    "Affinity Publisher",
    "Adobe Premiere Pro",
    "Final Cut Pro X",
    "Adobe After Effects",
    "DaVinci Resolve",
    "iMovie",
    "Camtasia",
    "Filmora",
    "Vegas Pro",
    "Lightworks",
    "CyberLink PowerDirector",
    "Adobe Audition",
    "Audacity",
    "FL Studio",
    "Ableton Live",
    "Logic Pro X",
    "Pro Tools",
    "GarageBand",
    "Reaper",
    "Cubase",
    "PreSonus Studio One",
    "Zoho CRM",
    "Salesforce",
    "Microsoft Dynamics 365",
    "HubSpot CRM",
    "SAP CRM",
    "Oracle CRM",
    "Pipedrive",
    "Freshsales",
    "Insightly",
    "Nimble",
]

digital_5 = [
    "SugarCRM",
    "NetSuite CRM",
    "Zoho Books",
    "QuickBooks Online",
    "FreshBooks",
    "Xero",
    "Wave Financial",
    "Sage Business Cloud Accounting",
    "Kashoo",
    "Zoho Invoice",
    "Invoicera",
    "Invoice Ninja",
    "Invoice2go",
    "Square Invoices",
    "Bill.com",
    "BQE Core",
    "TimeSolv",
    "BigTime",
    "Function Point",
    "Mavenlink",
    "Projector PSA",
    "Accelo",
    "ConnectWise Manage",
    "Workamajig",
    "NetSuite OpenAir",
    "NetSuite ERP",
    "SAP S/4HANA",
    "Oracle ERP Cloud",
    "Microsoft Dynamics 365 Finance",
    "Sage Intacct",
    "Acumatica",
    "Odoo",
    "Infor CloudSuite Financials",
    "Epicor ERP",
    "SYSPRO",
    "IQMS ERP",
    "Plex Systems",
    "Workday Financial Management",
    "Deltek Costpoint",
    "Brightpearl",
    "SAP Business One",
    "Microsoft Dynamics GP",
    "QuickBooks Desktop Enterprise",
    "Sage 100cloud",
    "Oracle NetSuite",
    "Microsoft Dynamics NAV",
    "Epicor Vista",
    "SAP Business ByDesign",
    "Priority Software",
    "Infor LN",
    "Epicor Prophet 21",
    "Microsoft Dynamics SL",
    "Sage 300cloud",
    "Infor M3",
    "DELMIAworks",
    "Workday HCM",
    "Oracle HCM Cloud",
    "SAP SuccessFactors",
    "UltiPro",
    "ADP Workforce Now",
    "Ceridian Dayforce",
    "Paycom",
    "Kronos Workforce Ready",
    "BambooHR",
    "Namely",
    "Zenefits",
    "Paylocity",
    "Gusto",
    "Rippling",
    "ADP Vantage HCM",
    "iCIMS Talent Acquisition Suite",
    "Jobvite",
    "Workable",
    "Greenhouse",
    "Breezy HR",
    "Lever",
    "SmartRecruiters",
    "Zoho Recruit",
    "Bullhorn ATS & CRM",
    "JazzHR",
    "PCRecruiter",
    "Crelate Talent",
    "Avature ATS",
    "Resumate",
    "Newton ATS",
    "SAP Concur",
    "Expensify",
    "Zoho Expense",
    "Rydoo",
    "Certify",
    "Abacus",
    "Receipt Bank",
    "Chrome River EXPENSE",
    "Coupa Expense Management",
    "Tallie",
    "ExpenseWire",
    "Nexonia Expenses",
    "Replicon",
    "SutiExpense",
    "DATABASICS Expense",
    "Emburse Certify Expense",
    "Zoho Inventory",
    "TradeGecko",
    "QuickBooks Commerce",
    "Cin7",
    "NetSuite ERP",
    "Odoo",
    "Zoho Books",
    "DEAR Inventory",
    "Unleashed",
    "Orderhive",
    "Fishbowl",
    "Megaventory",
    "Brightpearl",
    "Ecomdash",
]

digital_6 = [
    "ChannelAdvisor",
    "Stitch Labs",
    "TradeGecko",
    "Veeqo",
    "Freestyle Solutions",
    "Orderbot",
    "Skubana",
    "Sellbrite",
    "Katana",
    "Jazva",
    "Infoplus",
    "Acumatica Commerce Edition",
    "Brightpearl",
    "SAP Integrated Business Planning",
    "Oracle SCM Cloud",
    "Blue Yonder Luminate Planning",
    "E2open",
    "Kinaxis RapidResponse",
    "Infor Nexus",
    "Anaplan",
    "Manhattan Active Inventory",
    "RELEX Solutions",
    "Logility Inventory Optimization",
    "ToolsGroup SO99+",
    "Demand Solutions DSX",
    "GAINSystems",
    "JustEnough",
    "Neogrid",
    "SAS Inventory Optimization Workbench",
    "Arkieva",
    "Vanguard Predictive Planning",
    "Netstock",
    "Smart IP&O",
    "Avercast",
    "DemandCaster",
    "StockIQ",
    "Valogix Inventory Planner",
    "JDA Demand Planning",
    "AFS Retail Execution",
    "Aspen Supply Chain Planner",
    "HighJump Supply Chain Advantage in The Cloud",
    "Kechie ERP",
    "MicroMain CMMS",
    "Hippo CMMS",
    "Maintenance Connection",
    "eMaint CMMS",
    "Fiix",
    "UpKeep",
    "Asset Essentials",
    "ManagerPlus",
    "Limble CMMS",
    "Maxpanda",
    "EZOfficeInventory",
    "Fleetio",
    "Aviation InterTec Services",
    "Q Ware CMMS",
    "MPulse",
    "MaintiMizer",
    "Dude Solutions Asset Essentials",
    "Tenna",
    "FaciliWorks CMMS",
    "FTMaintenance",
    "Cetaris Fleet",
    "Sage Fixed Assets",
    "IBM Maximo",
    "ServiceMax",
    "IFS Field Service Management",
    "Oracle Field Service Cloud",
    "Microsoft Dynamics 365 Field Service",
    "ServiceTitan",
    "Jobber",
    "Housecall Pro",
    "mHelpDesk",
    "ThermoGRID",
    "FieldEdge",
    "Astea Alliance",
    "ServiceTrade Commercial",
    "Workiz",
    "FieldPulse",
    "Service Fusion",
    "Service Autopilot",
    "Kickserv",
    "GeoOp",
    "BlueFolder",
    "Synchroteam",
    "FieldEZ",
    "ReachOut Suite",
    "ServiceM8",
    "ProntoForms",
    "simPRO",
    "RazorSync",
    "Wintac",
    "Commusoft",
    "FieldAware",
    "Less Paper Co.",
    "Klipfolio",
    "Zoho Analytics",
    "Tableau",
    "Domo",
    "QlikView",
    "Sisense",
    "Looker",
    "Microsoft Power BI",
    "SAP BusinessObjects",
    "IBM Cognos Analytics",
    "Oracle Business Intelligence",
    "GoodData",
    "MicroStrategy",
    "Dundas BI",
    "Yellowfin BI",
    "Birst",
    "Jaspersoft",
    "SAS Business Intelligence",
    "ThoughtSpot",
    "Logi Analytics",
]

services_1 = [
    {"product": service, "category": "SERVICE"}
    for service in [
        "Landscaping",
        "Gardening",
        "Plumbing",
        "Electrician",
        "House Cleaning",
        "Car Repair",
        "Carpentry",
        "Roofing",
        "Pest Control",
        "Pool Cleaning",
        "Snow Removal",
        "Home Renovation",
        "Interior Painting",
        "Exterior Painting",
        "Flooring Installation",
        "Tiling",
        "Fence Installation",
        "Deck Building",
        "Drywall Installation",
        "Insulation Installation",
        "Air Duct Cleaning",
        "Window Cleaning",
        "Gutter Cleaning",
        "Chimney Cleaning",
        "Septic Tank Services",
        "Well Drilling",
        "Sprinkler System Installation",
        "Garage Door Installation",
        "Garbage Collection",
        "Recycling Services",
        "Junk Removal",
        "Moving Services",
        "Storage Services",
        "Courier Services",
        "Notary Services",
        "Laundry Services",
        "Tailoring Services",
        "Appraisal Services",
        "Home Inspection",
        "Surveying",
        "Property Management",
        "Real Estate Agent Services",
        "Architectural Services",
        "Home Staging",
        "House Sitting",
        "Pet Sitting",
        "Dog Walking",
        "Veterinary Services",
        "Mobile Pet Grooming",
        "Aquarium Maintenance",
        "Pet Training",
        "Piano Tuning",
        "Art Restoration",
        "Furniture Restoration",
        "Car Detailing",
        "Boat Cleaning",
        "Drone Photography",
        "Virtual Tour Services",
        "Wedding Officiant Services",
        "Babysitting",
        "Tutoring",
        "Language Lessons",
        "Music Lessons",
        "Dance Lessons",
        "Art Classes",
        "Cooking Classes",
        "Culinary Tours",
        "Wine Tasting Tours",
        "Brewery Tours",
        "Scenic Flights",
        "Hot Air Balloon Rides",
        "Personal Shopper",
        "Concierge Services",
        "Event Planning",
        "Party Supplies Rental",
        "Catering Services",
        "Bartender Services",
        "Clown Services",
        "Magician Services",
        "Face Painting",
        "Bounce House Rentals",
        "Limo Services",
        "Valet Parking",
        "Security Guard Services",
        "Personal Trainer",
        "Yoga Instructor",
        "Nutritionist",
        "Mental Health Counseling",
        "Acupuncture",
        "Massage Therapy",
        "Chiropractor",
        "Physiotherapy",
        "Speech Therapy",
        "Occupational Therapy",
        "Podiatry Services",
        "Home Healthcare",
        "Nanny Services",
        "Senior Care",
        "Disability Services",
        "Telemedicine Services",
        "Tax Preparation",
        "Accounting",
        "Bookkeeping",
        "Financial Planning",
        "Insurance Brokerage",
        "Legal Services",
        "Private Investigation",
        "Transcription Services",
        "Copywriting Services",
        "SEO Services",
        "Social Media Management",
        "Graphic Design",
        "Web Development",
        "Software Development",
    ]
]

services_2 = [
    {"product": service, "category": "SERVICE"}
    for service in [
        "Carpet Cleaning",
        "Upholstery Cleaning",
        "Window Washing",
        "Maid Service",
        "Chimney Sweep",
        "Pressure Washing",
        "Graffiti Removal",
        "Gutter Cleaning",
        "House Sitters",
        "Lawn Service",
        "Tree Service",
        "Hauling",
        "Septic Tank Service",
        "Pest Control",
        "Beautician",
        "Makeup Artist",
        "Personal Stylist",
        "Image Consultant",
        "Wedding Planner",
        "Event Coordinator",
        "DJ Service",
        "Live Band",
        "Karaoke Services",
        "Personal Chef",
        "Caterer",
        "Bartender",
        "Mobile Spa",
        "Home Theater Installation",
        "Mobile Phone Repair",
        "Garden Designer",
        "Landscape Architect",
        "Fence Contractors",
        "Paving Contractors",
        "Solar Panel Installation",
        "Security System Installation",
        "Locksmith",
        "Home Organizer",
        "Feng Shui Consulting",
        "Custom Closet Design",
        "Pool Services",
        "Pond Services",
        "Aquarium Services",
        "Snow Removal",
        "Home Staging",
        "Real Estate Photography",
        "Interior Design",
        "Furniture Rental",
        "Aerial Photography",
        "Virtual Tour Services",
        "Voice Over",
        "Audio Editing",
        "Video Editing",
        "Animation Services",
        "Web Design",
        "SEO Services",
        "Content Marketing",
        "Social Media Marketing",
        "PPC Management",
        "Email Marketing",
        "Affiliate Marketing",
        "Public Relations",
        "Brand Consulting",
        "Market Research",
        "Business Consulting",
        "Financial Consulting",
        "HR Consulting",
        "IT Consulting",
        "Legal Consulting",
        "Medical Consulting",
        "Educational Consulting",
        "Immigration Consulting",
        "Translation Services",
        "Interpretation Services",
        "Writing Services",
        "Editing Services",
        "Proofreading Services",
        "Resume Services",
        "Career Coaching",
        "Business Coaching",
        "Executive Coaching",
        "Life Coaching",
        "Health Coaching",
        "Wellness Coaching",
        "Nutrition Coaching",
        "Fitness Coaching",
        "Yoga Instruction",
        "Meditation Instruction",
        "Spiritual Coaching",
        "Art Classes",
        "Craft Classes",
        "Cooking Classes",
        "Dance Classes",
        "Music Classes",
        "Photography Classes",
        "Writing Classes",
        "Language Classes",
        "Tutoring Services",
        "Test Prep Services",
        "Home Schooling",
        "Special Needs Education",
        "Early Childhood Education",
        "Adult Education",
        "Online Learning",
        "Workshop Facilitation",
        "Keynote Speaking",
        "Corporate Training",
        "Team Building Facilitation",
        "Retreat Facilitation",
    ]
]

services_3 = [
    {"product": service, "category": "SERVICE"}
    for service in [
        "Airport Shuttle Service",
        "Chauffeur Service",
        "Limousine Service",
        "Taxi Service",
        "Car Rental",
        "RV Rental",
        "Boat Rental",
        "Jet Ski Rental",
        "Bicycle Rental",
        "Scooter Rental",
        "Equipment Rental",
        "Tool Rental",
        "Party Supply Rental",
        "Furniture Rental",
        "Appliance Rental",
        "Self Storage",
        "Warehouse Storage",
        "Document Storage",
        "Cold Storage",
        "Wine Storage",
        "Laundry Service",
        "Dry Cleaning",
        "Alteration Service",
        "Shoe Repair",
        "Watch Repair",
        "Jewelry Repair",
        "Mobile Repair",
        "Appliance Repair",
        "Plumbing Repair",
        "Electrical Repair",
        "HVAC Repair",
        "Roof Repair",
        "Fence Repair",
        "Deck Repair",
        "Lawn Mower Repair",
        "Piano Tuning",
        "Musical Instrument Repair",
        "Computer Repair",
        "Data Recovery Service",
        "Virus Removal Service",
        "3D Printing Service",
        "Engraving Service",
        "Lamination Service",
        "Embroidery Service",
        "Printing Service",
        "Direct Mail Service",
        "Courier Service",
        "Shipping Service",
        "Freight Service",
        "Warehousing Service",
        "Telemarketing Service",
        "Answering Service",
        "Virtual Assistant Service",
        "Transcription Service",
        "Translation Service",
        "Notary Service",
        "Legal Service",
        "Mediation Service",
        "Paralegal Service",
        "Private Investigation Service",
        "Security Service",
        "Bodyguard Service",
        "Fire Safety Service",
        "Emergency Management Service",
        "Disaster Recovery Service",
        "Pest Control Service",
        "Animal Control Service",
        "Mold Removal Service",
        "Asbestos Removal Service",
        "Lead Removal Service",
        "Demolition Service",
        "Excavation Service",
        "Land Clearing Service",
        "Snow Removal Service",
        "Waste Management Service",
        "Recycling Service",
        "Junk Removal Service",
        "Tree Removal Service",
        "Stump Grinding Service",
        "Landscape Service",
        "Garden Service",
        "Lawn Service",
        "Sprinkler System Service",
        "Pond Cleaning Service",
        "Pool Cleaning Service",
        "Chimney Cleaning Service",
        "Gutter Cleaning Service",
        "Window Cleaning Service",
        "Pressure Washing Service",
        "Carpet Cleaning Service",
        "Upholstery Cleaning Service",
        "Duct Cleaning Service",
        "Septic Tank Cleaning Service",
        "Drain Cleaning Service",
        "Sewer Cleaning Service",
    ]
]

services_4 = [
    {"product": service, "category": "SERVICE"}
    for service in [
        "Event Photography",
        "Wedding Photography",
        "Portrait Photography",
        "Commercial Photography",
        "Aerial Photography",
        "Product Photography",
        "Real Estate Photography",
        "Sports Photography",
        "Nature Photography",
        "Photo Editing Service",
        "Film Production",
        "Video Production",
        "Music Production",
        "Podcast Production",
        "Audio Production",
        "Media Duplication",
        "Color Grading Service",
        "Sound Editing Service",
        "VFX Service",
        "Animation Service",
        "Event Planning",
        "Wedding Planning",
        "Conference Planning",
        "Corporate Event Planning",
        "Trade Show Planning",
        "Party Planning",
        "Catering Service",
        "DJ Service",
        "Live Music Service",
        "Entertainment Service",
        "Magician Service",
        "Clown Service",
        "Bouncy Castle Rental",
        "Costume Rental",
        "Table & Chair Rental",
        "Flower Arrangement Service",
        "Balloon Service",
        "Gift Wrapping Service",
        "Personal Shopper",
        "Concierge Service",
        "House Sitting",
        "Pet Sitting",
        "Dog Walking",
        "Animal Training",
        "Pet Grooming",
        "Mobile Pet Grooming",
        "Aquarium Maintenance",
        "Horse Boarding",
        "Pet Adoption Service",
        "Veterinary Service",
        "Massage Therapy",
        "Physical Therapy",
        "Occupational Therapy",
        "Speech Therapy",
        "Behavioral Therapy",
        "Chiropractic Service",
        "Acupuncture Service",
        "Nutritional Counseling",
        "Dietitian Service",
        "Personal Training",
        "Yoga Instruction",
        "Pilates Instruction",
        "Martial Arts Instruction",
        "Dance Instruction",
        "Music Instruction",
        "Art Instruction",
        "Cooking Instruction",
        "Language Instruction",
        "Driving Instruction",
        "Flight Instruction",
        "Boat Instruction",
        "Ski Instruction",
        "Golf Instruction",
        "Tennis Instruction",
        "Swimming Instruction",
        "Fitness Class",
        "Wellness Retreat",
        "Health Seminar",
        "Nutrition Workshop",
        "Cooking Workshop",
        "Art Workshop",
        "Writing Workshop",
        "Photography Workshop",
        "Music Workshop",
        "Dance Workshop",
        "Business Workshop",
        "Marketing Workshop",
        "Technology Workshop",
        "Skill Building Workshop",
        "Team Building Workshop",
        "Financial Planning",
        "Investment Advisory",
        "Tax Advisory",
        "Legal Advisory",
        "Real Estate Advisory",
        "Insurance Brokerage",
        "Mortgage Brokerage",
        "Credit Counseling",
        "Debt Counseling",
        "Retirement Planning",
        "Wealth Management",
        "Asset Management",
        "Trust Services",
        "Estate Planning",
        "Family Office Services",
    ]
]

services_5 = [
    {"product": service, "category": "SERVICE"}
    for service in [
        "Architectural Design",
        "Interior Design",
        "Landscape Design",
        "Web Design",
        "Logo Design",
        "Branding Service",
        "SEO Service",
        "Content Marketing",
        "Social Media Marketing",
        "PR Service",
        "Advertising Service",
        "Media Buying Service",
        "Market Research",
        "Survey Service",
        "Analytics Service",
        "Consulting Service",
        "Business Coaching",
        "Executive Coaching",
        "Career Coaching",
        "Spiritual Coaching",
        "Relationship Coaching",
        "Parenting Coaching",
        "Grief Counseling",
        "Psychotherapy",
        "Hypnotherapy",
        "Art Therapy",
        "Music Therapy",
        "Drama Therapy",
        "Home Renovation",
        "Basement Finishing",
        "Kitchen Renovation",
        "Bathroom Renovation",
        "Deck Building",
        "Fence Installation",
        "Roofing Service",
        "Siding Service",
        "Window Installation",
        "Door Installation",
        "Flooring Service",
        "Painting Service",
        "Drywall Service",
        "Insulation Service",
        "Electrical Service",
        "Plumbing Service",
        "HVAC Service",
        "Fireplace Installation",
        "Pool Installation",
        "Spa Installation",
        "Lawn Installation",
        "Garden Installation",
        "Irrigation Installation",
        "Lighting Installation",
        "Security System Installation",
        "Moving Service",
        "Packing Service",
        "Unpacking Service",
        "Cleaning Service",
        "Junk Removal Service",
        "Snow Removal Service",
        "Tree Removal Service",
        "Demolition Service",
        "Excavation Service",
        "Asphalt Sealing Service",
        "Paving Service",
        "Concrete Service",
        "Foundation Service",
        "Masonry Service",
        "Chimney Service",
        "Carpet Installation",
        "Tile Installation",
        "Countertop Installation",
        "Cabinet Installation",
        "Furniture Assembly",
        "Appliance Installation",
        "Appliance Repair",
        "Mobile Phone Repair",
        "Watch Repair",
        "Jewelry Repair",
        "Shoe Repair",
        "Leather Repair",
        "Upholstery Repair",
        "Instrument Repair",
        "Tool Repair",
        "Engine Repair",
        "Vehicle Repair",
        "Bicycle Repair",
        "Boat Repair",
        "Aircraft Repair",
        "Home Inspection",
        "Pest Inspection",
        "Mold Inspection",
        "Energy Audit",
        "Accessibility Services",
        "Elevator Installation",
        "Handyman Services",
        "Tutoring Services",
        "Translation Services",
    ]
]

generic_digital = [
    {"product": saas, "category": "DIGITAL"}
    for saas in [
        "users",
        "licences",
        "seats",
        "data storage",
    ]
]

generic_services = [
    {"product": service, "category": "SERVICES"}
    for service in [
        "services",
        "service",
        "onboarding",
        "implemenation",
        "setup",
    ]
]


data = []

for group in [
    physical_1,
    physical_2,
    physical_3,
    physical_4,
    physical_5,
    physical_6,
]:
    data.extend([{"product": item, "category": "PHYSICAL"} for item in group])

for group in [
    digital_1,
    digital_2,
    digital_3,
    digital_4,
    digital_5,
    digital_6,
]:
    data.extend([{"product": item, "category": "DIGITAL"} for item in group])

data.extend(services_1)
data.extend(services_2)
data.extend(services_3)
data.extend(services_4)
data.extend(services_5)

data.extend(generic_digital)
data.extend(generic_services)


def get_data():
    return data
